### ISSUE TITLE
Failed to respond error - 404

### ISSUE THREAD

**Issue by lamaj-productions** [Tueska/fl-HowLongToBeat#5]
I installed the plugin today, and I have been consistently been seeing 'failed to respond' errors. The response tells me to include the below log file and message for investigation.
I have tried reinstalling the plugin, and kill/open Flow Launcher, however I continue to see this error.

[2024-08-12.txt](https://github.com/user-attachments/files/16576932/2024-08-12.txt)

```
Flow Launcher version: 1.18.0
OS Version: 22631.3880
IntPtr Length: 8
x64: True

Python Path: C:\Users\User\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: C:\Users\User\AppData\Roaming\FlowLauncher\Environments\Node.js\Node-v16.18.0\node-v16.18.0-win-x64\node.exe
Date: 08/12/2024 12:31:55
Exception:
How Long To Beat Exception: 
Websites: https://github.com/Tueska/fl-howlongtobeat
Author: Tueska
Version: 1.0.1
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:96
                    throw new Error(error);
                          ^

Error: Error: Request failed with status code 404
    at HltbSearch.<anonymous> (C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:96:27)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:5:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

 ---> System.IO.InvalidDataException: C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:96
                    throw new Error(error);
                          ^

Error: Error: Request failed with status code 404
    at HltbSearch.<anonymous> (C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:96:27)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\User\AppData\Roaming\FlowLauncher\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:5:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 249
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 249
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 264
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 196
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 230
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 224
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 307
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by EsdrubalMagano** [comment]
I can confirm I have the same issue

**Comment by EsdrubalMagano** [comment]
Please open new issue in: https://github.com/Tueska/fl-howlongtobeat/issues
1. upload log file: C:\Users\\AppData\Roaming\FlowLauncher\Logs\1.18.0\2024-08-16.txt
2. copy below exception message

Flow Launcher version: 1.18.0
OS Version: 22631.4037
IntPtr Length: 8
x64: True

Python Path: C:\Users\\AppData\Local\Programs\Python\Python312\pythonw.exe
Node Path: C:\Program Files (x86)\nodejs\node.exe
Date: 08/16/2024 01:04:31
Exception:
How Long To Beat Exception: 
Websites: https://github.com/Tueska/fl-howlongtobeat
Author: Tueska
Version: 1.0.1
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: C:\Users\idris\AppData\Roaming\FlowLauncher\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:96
                    throw new Error(error);
                          ^

Error: Error: Request failed with status code 404
    at HltbSearch.<anonymous> (C:\Users\idris\AppData\Roaming\FlowLauncher\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:96:27)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\idris\AppData\Roaming\FlowLauncher\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:5:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.16.0

 ---> System.IO.InvalidDataException: C:\Users\idris\AppData\Roaming\FlowLauncher\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:96
                    throw new Error(error);
                          ^

Error: Error: Request failed with status code 404
    at HltbSearch.<anonymous> (C:\Users\idris\AppData\Roaming\FlowLauncher\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:96:27)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\idris\AppData\Roaming\FlowLauncher\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:5:65)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v18.16.0

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 249
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 249
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 264
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 196
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 230
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 224
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 307
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by W1p3out** [comment]
Same issue here since a moment for now. Awesome plugin by the way!

Flow Launcher version: 1.19.0
OS Version: 26120.1350
IntPtr Length: 8
x64: True

Python Path: 
Node Path: C:\Utilitaires\FlowLauncher\app-1.19.0\UserData\Environments\Node.js\Node-v16.18.0\node-v16.18.0-win-x64\node.exe
Date: 08/16/2024 10:21:22
Exception:
How Long To Beat Exception: 
Websites: https://github.com/Tueska/fl-howlongtobeat
Author: Tueska
Version: 1.0.1
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: C:\Utilitaires\FlowLauncher\app-1.19.0\UserData\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:96
                    throw new Error(error);
                          ^

Error: Error: Request failed with status code 404
    at HltbSearch.<anonymous> (C:\Utilitaires\FlowLauncher\app-1.19.0\UserData\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:96:27)
    at Generator.throw (<anonymous>)
    at rejected (C:\Utilitaires\FlowLauncher\app-1.19.0\UserData\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:5:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

 ---> System.IO.InvalidDataException: C:\Utilitaires\FlowLauncher\app-1.19.0\UserData\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:96
                    throw new Error(error);
                          ^

Error: Error: Request failed with status code 404
    at HltbSearch.<anonymous> (C:\Utilitaires\FlowLauncher\app-1.19.0\UserData\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:96:27)
    at Generator.throw (<anonymous>)
    at rejected (C:\Utilitaires\FlowLauncher\app-1.19.0\UserData\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:5:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 249
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 249
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 261
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass28_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 248
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 282
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass28_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 276
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 389
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by lamaj-productions** [comment]
I did a little investigation, and it looks like there was an update on the HowLongToBeat API, causing issues for integrations like this plugin.

@Tueska you referenced another repo in your post by ckatzorka, there is a raised issue over there as well [LINK](https://github.com/ckatzorke/howlongtobeat/issues/63).

Someone in that thread referenced _another_ API, and the issue raised there appears to have been fixed. [LINK](https://github.com/ScrappyCocco/HowLongToBeat-PythonAPI/issues/25).

Hopefully this helps!
