### ISSUE TITLE
how log to beat broken on v1.19

### ISSUE THREAD

**Issue by indigofairyx** [Tueska/fl-HowLongToBeat#6]
version 1.19 seems to have broken a few different plugins. 

beat is one of them.

I've tired uninstalling\reinstalling, no luck.

```

Please open new issue in: https://github.com/Tueska/fl-howlongtobeat/issues
1. upload log file: C:\Users\CLOUDEN\AppData\Roaming\FlowLauncher\Logs\1.19.0\2024-09-04.txt
2. copy below exception message

Flow Launcher version: 1.19.0
OS Version: 19045.2965
IntPtr Length: 8
x64: True

Python Path: C:\Users\CLOUDEN\AppData\Local\Programs\Python\Python310\python.exe
Node Path: C:\Users\CLOUDEN\AppData\Roaming\FlowLauncher\Environments\Node.js\Node-v16.18.0\node-v16.18.0-win-x64\node.exe
Date: 09/04/2024 23:54:08
Exception:
How Long To Beat Exception: 
Websites: https://github.com/Tueska/fl-howlongtobeat
Author: Tueska
Version: 1.0.1
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: C:\Users\CLOUDEN\AppData\Roaming\FlowLauncher\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:96
                    throw new Error(error);
                          ^

Error: Error: Request failed with status code 404
    at HltbSearch.<anonymous> (C:\Users\CLOUDEN\AppData\Roaming\FlowLauncher\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:96:27)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\CLOUDEN\AppData\Roaming\FlowLauncher\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:5:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

 ---> System.IO.InvalidDataException: C:\Users\CLOUDEN\AppData\Roaming\FlowLauncher\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:96
                    throw new Error(error);
                          ^

Error: Error: Request failed with status code 404
    at HltbSearch.<anonymous> (C:\Users\CLOUDEN\AppData\Roaming\FlowLauncher\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:96:27)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\CLOUDEN\AppData\Roaming\FlowLauncher\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:5:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 249
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 249
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 264
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass28_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 248
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 282
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass28_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 276
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 389
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)


```

**Comment by Orhunaa** [comment]
Likewise broken
```
Please open new issue in: https://github.com/Tueska/fl-howlongtobeat/issues
1. upload log file: C:\Users\X\AppData\Roaming\FlowLauncher\Logs\1.19.4\2024-12-01.txt
2. copy below exception message

Flow Launcher version: 1.19.4
OS Version: 22631.4460
IntPtr Length: 8
x64: True

Python Path: C:\Users\X\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: C:\Users\X\AppData\Roaming\FlowLauncher\Environments\Node.js\Node-v16.18.0\node-v16.18.0-win-x64\node.exe
Date: 12/01/2024 13:42:36
Exception:
How Long To Beat Exception: 
Websites: https://github.com/Tueska/fl-howlongtobeat
Author: Tueska
Version: 1.0.1
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: C:\Users\X\AppData\Roaming\FlowLauncher\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:96
                    throw new Error(error);
                          ^

Error: Error: Request failed with status code 404
    at HltbSearch.<anonymous> (C:\Users\X\AppData\Roaming\FlowLauncher\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:96:27)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\X\AppData\Roaming\FlowLauncher\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:5:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

 ---> System.IO.InvalidDataException: C:\Users\X\AppData\Roaming\FlowLauncher\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:96
                    throw new Error(error);
                          ^

Error: Error: Request failed with status code 404
    at HltbSearch.<anonymous> (C:\Users\X\AppData\Roaming\FlowLauncher\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:96:27)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\X\AppData\Roaming\FlowLauncher\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:5:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 249
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 249
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 264
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass28_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 248
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 282
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass28_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 276
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 389
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

**Comment by Jalaj1087** [comment]
Noticed this problem is yet not solved after I downloaded it again today.

`
Please open new issue in: https://github.com/Tueska/fl-howlongtobeat/issues
1. upload log file: C:\Users\admin\AppData\Roaming\FlowLauncher\Logs\1.19.4\2024-12-26.txt
2. copy below exception message

Flow Launcher version: 1.19.4
OS Version: 19045.5247
IntPtr Length: 8
x64: True

Python Path: C:\Users\admin\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: C:\Users\admin\AppData\Roaming\FlowLauncher\Environments\Node.js\Node-v16.18.0\node-v16.18.0-win-x64\node.exe
Date: 12/26/2024 17:38:31
Exception:
How Long To Beat Exception: 
Websites: https://github.com/Tueska/fl-howlongtobeat
Author: Tueska
Version: 1.0.1
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: C:\Users\admin\AppData\Roaming\FlowLauncher\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:96
                    throw new Error(error);
                          ^

Error: Error: Request failed with status code 404
    at HltbSearch.<anonymous> (C:\Users\admin\AppData\Roaming\FlowLauncher\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:96:27)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\admin\AppData\Roaming\FlowLauncher\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:5:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

 ---> System.IO.InvalidDataException: C:\Users\admin\AppData\Roaming\FlowLauncher\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:96
                    throw new Error(error);
                          ^

Error: Error: Request failed with status code 404
    at HltbSearch.<anonymous> (C:\Users\admin\AppData\Roaming\FlowLauncher\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:96:27)
    at Generator.throw (<anonymous>)
    at rejected (C:\Users\admin\AppData\Roaming\FlowLauncher\Plugins\How Long To Beat-1.0.1\node_modules\howlongtobeat\dist\main\hltbsearch.js:5:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 249
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 249
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 264
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass28_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 248
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 282
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass28_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 276
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 389
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

`
